### ISSUE TITLE
Not work properly, pls help (win 11 64-bit)

### ISSUE THREAD

**Issue by AdonNeet** [Zukaritasu/notepadpp_rpc#4]
I was install the plugin but it didnt work

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by Zukaritasu** [comment]
Hello! First I need information from your system to solve the problem
- What version of Windows do you have?
- 32 or 64 bit architecture?
- The version of Notepad++ you have
- The DiscordRPC plugin version

**Comment by AdonNeet** [comment]
uhh ohh, wait
windows 11 64-bit
Notepad++ V8.4.6
DiscordRPC version is 1.4.262.1

**Comment by Zukaritasu** [comment]
Do you use discord from the browser or from the desktop application? The plugin has no support to show the rich presence from the browser

If you use the desktop app, you can try deleting the following folder C:\Users\your user\AppData\Local\DiscordRPC that will cause the plugin settings to be reset

If the above did not work for you, you can join my discord server and there we can quickly solve the problem https://discord.gg/JTSVh8chcx
