### ISSUE TITLE
"DiscordRPC is not compatible with this version of Notepad++"

### ISSUE THREAD

**Issue by ahinojos0029** [Zukaritasu/notepadpp_rpc#6]
Windows 11
Notepad++ version: 8.5.6
64 bit
DiscordRPC version: 1.6.6

**Comment by Zukaritasu** [comment]
The plugin has been tested on Windows 10 64 bit and Windows 11 64 bit with the latest version of Notepad++ 8.5.6 without any problems. Does Notepad++ show any errors? If possible please show an image of the error.
